// themes/defaultTheme.ts
import { Theme } from './Theme';

export const defaultTheme: Theme = {
  CheckBox: {
    wrapper: 'mb-6',
    row: 'flex flex-row items-center gap-2',
    label: 'text-[14px] text-slate-600 font-roboto text-center md:text-left',
    labelWrapper: 'mt-1',
    input: 'appearance-none w-5 h-5 border border-slate-300 rounded-sm disabled:opacity-50 disabled:cursor-not-allowed scale-[1.1] bg-white checked:bg-blue-600 relative',
    invalid: 'ring-2 ring-red-500',
    checkmark: 'absolute top-[-4px] left-[-2px] w-7 h-7 pointer-events-none',
  },
  Toggle: {
    wrapper: 'mb-6',
    row: 'flex items-center gap-2',
    label: 'text-[14px] text-slate-600 font-roboto',
    labelWrapper: 'mb-1',
    toggle: 'relative inline-block w-12 h-6 rounded-full transition-colors duration-300 cursor-pointer',
    handle: 'absolute left-0 top-0 w-6 h-6 bg-white rounded-full transition-transform duration-300 transform',
  },
  RadioButton: {
    wrapper: 'mb-6',
    row: 'flex flex-row items-center gap-2',
    label: 'text-[14px] text-slate-600 font-roboto text-center md:text-left',
    labelWrapper: 'mt-1',
    input: 'appearance-none w-5 h-5 border border-slate-300 rounded-full checked:bg-blue-600 checked:border-transparent disabled:opacity-50 disabled:cursor-not-allowed scale-[1]',
    invalid: 'ring-2 ring-red-500',
  },
  Input: {
    wrapper: "mb-6",
    row: "flex items-center gap-2",
    label: "text-[14px] text-slate-600 uppercase font-regular font-roboto mb-2",
    labelWrapper: "mb-1",
    input: "border bg-white text-[16px] text-slate-500 font-roboto placeholder-slate-300 px-4 py-4 rounded-md focus:outline-none focus:ring-2 disabled:bg-slate-100 disabled:text-slate-400 disabled:cursor-not-allowed w-full",
  },
  TextArea: {
    wrapper: 'mb-6',
    row: 'flex items-start gap-2',
    label: 'text-[14px] text-slate-600 uppercase font-regular font-roboto mb-2',
    labelWrapper: 'mb-1',
    textarea: 'border bg-white text-[16px] text-slate-500 font-roboto placeholder-slate-300 px-4 py-4 rounded-md focus:outline-none focus:ring-2 disabled:bg-slate-100 disabled:text-slate-400 disabled:cursor-not-allowed w-full',
  },
  CodeBlock: {
    container: 'my-6 rounded-md overflow-hidden border border-blue-950 bg-blue-950',
    title: 'px-4 py-2 text-sm font-medium text-blue-100 bg-blue-900 border-b border-blue-800 flex items-center justify-between',
    code: 'bg-blue-950 px-4 py-3 text-sm text-blue-200 overflow-x-auto whitespace-pre-wrap font-mono w-full resize-none',
  },
  Button: {
    base: 'flex items-center justify-center text-white font-roboto px-4 py-2 focus:outline-none transition-colors duration-300 cursor-pointer',
    rectangle: 'rounded-md',
    circle: 'rounded-full p-2',
    pill: 'rounded-full px-6',
    active: 'bg-blue-600 hover:bg-blue-700 active:bg-blue-800',
    disabled: 'opacity-50 cursor-not-allowed',
    content: 'flex items-center gap-2',
    materialSymbol: 'material-symbols-outlined text-white text-[20px]', 
  },
  DatePicker: {
    wrapper: 'relative flex items-center',
    input: 'border border-slate-300 bg-white text-[16px] text-slate-500 font-roboto placeholder-slate-300 px-4 py-4 rounded-md focus:outline-none disabled:bg-slate-100 disabled:text-slate-400 disabled:cursor-not-allowed w-full',
    iconWrapper: 'cursor-pointer flex items-center',
    popup: 'absolute top-full mt-2 w-[320px] bg-white border border-slate-300 rounded-md shadow-md z-50 p-4',
    header: 'flex justify-between items-center mb-2',
    monthLabel: 'font-semibold text-slate-700 text-[14px] font-roboto',
    monthNavButton: 'text-slate-600 hover:text-blue-600 text-[20px] font-roboto cursor-pointer',
    monthDivider: 'border-t border-stone-200 my-2',
    dayLabelsRow: 'grid grid-cols-7 text-xs text-slate-400 font-roboto mb-2 pt-2',
    calendar: 'grid grid-cols-7 gap-0 p-1',
    day: 'text-[14px] text-slate-600 font-roboto cursor-pointer',
    dayOutsideMonth: 'text-[14px] text-slate-300 font-roboto cursor-pointer', 
    daySelected: 'bg-blue-600 text-white',
    dayInRangeHover: 'bg-blue-300 text-slate-600',
    dayDisabled: 'opacity-30 cursor-not-allowed',
    dayLabel: 'flex justify-center items-center',
    footer: 'flex justify-center gap-2 mt-4',
    todayButton: 'text-blue-600 hover:underline text-sm font-roboto',  
    clearButtonWrapper: 'flex',
    clearButton: 'text-slate-500 hover:bg-slate-100 text-sm font-roboto border border-slate-300 rounded-md px-3 py-1 cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-300',
    quickSelectButtonWrapper: 'flex',
    quickSelectButton: 'text-blue-600 hover:bg-blue-100 text-xs font-roboto border border-blue-100 rounded-md px-3 py-1 cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-300',
  },
  FileUploader: {
    wrapper: 'border-2 border-dashed border-slate-300 rounded-md p-6 flex flex-col items-center justify-center gap-4 bg-white cursor-pointer transition-colors',
    dragActive: 'border-blue-400 bg-blue-50',
    text: 'text-slate-500 text-center text-sm font-roboto',
    browseButtonWrapper: 'flex justify-center mt-4',
    browseButton: 'bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center gap-2',
    errorText: 'text-red-500 text-xs mt-2 font-roboto text-center',
  },
  modal: {
    container: 'fixed inset-0 z-[9999] flex items-center justify-center p-4',
    overlay: 'absolute inset-0 bg-black/50 transition-opacity',
    modalCloseButton: 'absolute top-0 right-0 pt-4 pr-4 cursor-pointer',
    content: 'relative z-10 bg-white rounded-lg p-8 w-[50%] h-[50%] overflow-auto shadow-lg',
    toasterWrapper: 'fixed z-[9999] flex items-center justify-center p-4',
    toasterContent: 'bg-blue-600  text-white rounded-md shadow-md overflow-auto flex items-center justify-between gap-2 w-full min-h-[25px] p-2',
    toasterText: 'flex items-center  gap-2 overflow-hidden text-ellipsis whitespace-nowrap p-2',
    toasterCloseButton: 'flex items-center border-l border-slate-200 text-white justify-center cursor-pointer p-2',
    animateInTopLeft: 'animate-fade-in-down',
    animateOutTopLeft: 'animate-fade-out-up',
    animateInTopCenter: 'animate-slide-in-top',
    animateOutTopCenter: 'animate-slide-out-top',
    animateInTopRight: 'animate-fade-in-down',
    animateOutTopRight: 'animate-fade-out-up',
    animateInBottomLeft: 'animate-slide-in-bottom',
    animateOutBottomLeft: 'animate-slide-out-bottom',
    animateInBottomCenter: 'animate-slide-in-bottom',
    animateOutBottomCenter: 'animate-slide-out-bottom',
    animateInBottomRight: 'animate-slide-in-bottom',
    animateOutBottomRight: 'animate-slide-out-bottom',
    animateIn: 'animate-fade-in',
    animateOut: 'animate-fade-out',
    toasterPositionTopLeft: 'top-4 left-4',
    toasterPositionTopCenter: 'top-4 left-1/2 transform -translate-x-1/2',
    toasterPositionTopRight: 'top-4 right-4',
    toasterPositionBottomLeft: 'bottom-4 left-4',
    toasterPositionBottomCenter: 'bottom-4 left-1/2 transform -translate-x-1/2',
    toasterPositionBottomRight: 'bottom-4 right-4',
  },
  Select: {
    selectContainer: 'relative w-full mb-4',
    label: 'text-sm font-medium text-slate-700 font-roboto',
    select:
      'border border-slate-300 rounded-md bg-white text-slate-600 font-roboto',
    selectChevron: 'w-4 h-4 fill-current text-slate-600',
    selectOption:
      'text-sm text-slate-700 font-roboto hover:bg-slate-100 cursor-pointer',
    groupLabel:
      'px-4 py-2 text-xs font-semibold text-slate-500 uppercase bg-slate-50 font-roboto',
  },
  
};
